apiVersion: v1
kind: Pod
metadata:
  name: cpu-spike-py-sim
  namespace: koral-system
  labels:
    app: cpu-spike-py-sim
    role: simulation
spec:
  serviceAccountName: koral-agent
  containers:
    - name: cpu-spike
      image: DOCKERHUB_USERNAME/koral-simulation:latest
      env:
        - name: SCENARIO
          value: cpu_spike
      resources:
        limits:
          cpu: "1"
          memory: "128Mi"
  restartPolicy: Never
