apiVersion: v1
kind: Service
metadata:
  name: koral
  labels:
    app: koral
spec:
  type: NodePort
  selector:
    app: koral
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
