apiVersion: apps/v1
kind: Deployment
metadata:
  name: koral
  labels:
    app: koral
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koral
  template:
    metadata:
      labels:
        app: koral
    spec:
      containers:
        - name: koral
          image: koral:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
